# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_affiche', models.CharField(max_length=30)),
                ('lien', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('studio', models.CharField(max_length=30)),
                ('nb_episode_diffuse', models.IntegerField()),
                ('nb_episode_tot', models.IntegerField()),
                ('date_episode', models.DateField()),
                ('synopsis', models.TextField()),
                ('note', models.FloatField()),
                ('nb_vote', models.IntegerField()),
                ('tags', models.TextField()),
                ('affiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_anime.Affiche')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cover', models.CharField(max_length=30)),
                ('lien', models.TextField()),
                ('lien_a_venir', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_genre', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('auteur', models.CharField(max_length=40)),
                ('nb_tome_paru', models.IntegerField()),
                ('nb_tome_tot', models.IntegerField()),
                ('date_tome', models.DateField()),
                ('synopsis', models.TextField()),
                ('note', models.FloatField()),
                ('nb_vote', models.IntegerField()),
                ('tags', models.TextField()),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_anime.Cover')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manga_anime.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Planning_Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_anime.Anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Planning_Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_anime.Manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_anime.Genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_anime.Manga'),
        ),
    ]
